# Generated by Django 6.0.7 on 2026-07-12 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='Recruiter', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='freelancer',
            field=models.CharField(default='Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='pin',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='preview/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Locked', 'Locked'), ('Assigned', 'Assigned'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Disputed', 'Disputed'), ('Released', 'Released')], default='Locked', max_length=20),
        ),
    ]
